import { NotInterested, CheckOutlined } from "@mui/icons-material"
import { Box } from "@mui/material"

export const checkbizPlansItems = (current: boolean, highlighted: boolean): any => ({
    'es': {
        'freemium': <ul style={{ paddingInlineStart: 0 }}>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box>  Fichaje con geolocalización (GPS / geocerca)</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box>Control de horas trabajadas</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box>Gestión de empleados</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box>Asignación de empleados a la sucursal/proyecto disponible</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box>Validación de dispositivo de confianza (2FA)</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> Estadísticas y reportes en tiempo real</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box>Políticas de jornada, descanso y ubicación (flexible/estricto)</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> Informes y exportación (CSV)</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> Integraciones por Webhook</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> <strong>Métricas por empleado y por la sucursal/proyecto disponible</strong></Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box><strong>Soporte básico</strong> (consultas generales y asistencia limitada)</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10, marginTop: 40 }}> <NotInterested fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> <strong>Sucursales/proyectos</strong>: 1</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <NotInterested fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box><strong>Empleados</strong>: 10</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <NotInterested fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box><strong> Entidades</strong>: 1</Box></li>
        </ul>,

        'bronze': <ul style={{ paddingInlineStart: 0 }}>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> Todo lo del plan Gratis</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box><strong>Sucursales/proyectos ilimitados</strong></Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box><strong>Empleados ilimitados</strong></Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box><strong>Entidades ilimitadas</strong></Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box>Comparativas entre sucursales/proyectos</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> Integraciones por Webhook</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box><strong>Métricas por empleado y comparativas entre sucursales/proyectos</strong></Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box><strong>Soporte estándar</strong> (tiempos de respuesta definidos + ayuda operativa)</Box></li>
        </ul>,

        'enterprise': <ul style={{ paddingInlineStart: 0 }}>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box>Todo lo del plan Bronce</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box><strong>Soporte prioritario</strong> (canales preferentes)</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box><strong>Integraciones con ERP/CRM y desarrollos personalizados</strong> (bajo convenio)</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box><strong>Operación escalable para grandes organizaciones multi-entidad</strong></Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> Integraciones por Webhook</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box><strong>Métricas por empleado y comparativas entre sucursales/proyectos</strong></Box></li>
        </ul>
    },
    'en': {
        'freemium': <ul style={{ paddingInlineStart: 0 }}>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> Time tracking with geolocation (GPS / geofence)</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> Worked hours control</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> Employee management</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> Assignment of employees to the available branch/project</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> Trusted device validation (2FA)</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> Real-time statistics and reports</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> Workday, break, and location policies (flexible/strict)</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> Reports and export (CSV)</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> Webhook integrations</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> <strong>Metrics per employee and per available branch/project</strong></Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box><strong> Basic support</strong> (general inquiries and limited assistance)</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10, marginTop: 40 }}> <NotInterested fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> <strong>Branches/projects</strong>: 1</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <NotInterested fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> <strong>Employees</strong>: 10</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <NotInterested fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> <strong>Entities</strong>: 1</Box></li>
        </ul>,

        'bronze': <ul style={{ paddingInlineStart: 0 }}>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> Everything from the Free plan</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box><strong> Unlimited branches/projects</strong></Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box><strong> Unlimited employees</strong></Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> <strong>Unlimited entities</strong></Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> Branch/project comparisons</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> Webhook integrations</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> <strong>Metrics per employee and branch/project comparisons</strong></Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> <strong>Standard support</strong> (defined response times + operational assistance)</Box></li>
        </ul>,

        'enterprise': <ul style={{ paddingInlineStart: 0 }}>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> Everything from the Bronze plan</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> <strong>Priority support </strong>  (preferred channels)</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box><strong> ERP/CRM integrations and custom developments</strong> (under agreement) </Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> <strong>Scalable operation for large multi-entity organizations</strong></Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box> Webhook integrations</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display: 'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5, }} /> <Box><strong> Metrics per employee and branch/project comparisons</strong></Box></li>
        </ul>
    }
})