import { Cancel, CheckOutlined } from "@mui/icons-material"

export const checkbizPlansItems = (current: boolean, highlighted: boolean): any => ({
    'es': {
        'freemium': <ul style={{ paddingInlineStart: 0 }}>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5 }} />  Fichaje con geolocalización (GPS / geocerca)</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} />Control de horas trabajadas</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} />Gestión de empleados</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} />Asignación de empleados a la sucursal/proyecto disponible</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} />Validación de dispositivo de confianza (2FA)</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /> Estadísticas y reportes en tiempo real</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} />Políticas de jornada, descanso y ubicación (flexible/estricto)</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /> Informes y exportación (CSV)</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /> Integraciones por Webhook</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /> <strong>Métricas por empleado y por la sucursal/proyecto disponible</strong></li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /><strong>Soporte básico</strong> (consultas generales y asistencia limitada)</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2, marginTop:10 }}> <Cancel fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /> <strong>Sucursales/proyectos</strong>: 1</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <Cancel fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /><strong>Empleados</strong>: 10</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <Cancel fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /><strong> Entidades</strong>: 1</li>
        </ul>,

        'bronze': <ul style={{ paddingInlineStart: 0 }}>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /> Todo lo del plan Gratis</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /><strong>Sucursales/proyectos ilimitados</strong></li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /><strong>Empleados ilimitados</strong></li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /><strong>Entidades ilimitadas</strong></li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} />Comparativas entre sucursales/proyectos</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /><strong>Métricas por empleado y comparativas entre sucursales/proyectos</strong></li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /><strong>Soporte estándar</strong> (tiempos de respuesta definidos + ayuda operativa)</li>
        </ul>,

        'enterprise': <ul style={{ paddingInlineStart: 0 }}>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} />Todo lo del plan Bronce</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /><strong>Soporte prioritario</strong> (canales preferentes)</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /><strong>Integraciones con ERP/CRM y desarrollos personalizados</strong> (bajo convenio)</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /><strong>Operación escalable para grandes organizaciones multi-entidad</strong></li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /><strong>Métricas por empleado y comparativas entre sucursales/proyectos</strong></li>
        </ul>
    },
    'en': {
        'freemium': <ul style={{ paddingInlineStart: 0 }}>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /> Time tracking with geolocation (GPS / geofence)</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /> Worked hours control</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /> Employee management</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /> Assignment of employees to the available branch/project</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /> Trusted device validation (2FA)</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /> Real-time statistics and reports</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /> Workday, break, and location policies (flexible/strict)</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /> Reports and export (CSV)</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /> Webhook integrations</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /> <strong>Metrics per employee and per available branch/project</strong></li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /><strong> Basic support</strong> (general inquiries and limited assistance)</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2, marginTop:10 }}> <Cancel fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /> <strong>Branches/projects</strong>: 1</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <Cancel fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /> <strong>Employees</strong>: 10</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <Cancel fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /> <strong>Entities</strong>: 1</li>
        </ul>,

        'bronze': <ul style={{ paddingInlineStart: 0 }}>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /> Everything from the Free plan</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /><strong> Unlimited branches/projects</strong></li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /><strong> Unlimited employees</strong></li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /> <strong>Unlimited entities</strong></li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /> Branch/project comparisons</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /> <strong>Metrics per employee and branch/project comparisons</strong></li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /> <strong>Standard support</strong> (defined response times + operational assistance)</li>
        </ul>,

        'enterprise': <ul style={{ paddingInlineStart: 0 }}>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /> Everything from the Bronze plan</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /> <strong>Priority support </strong>  (preferred channels)</li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /><strong> ERP/CRM integrations and custom developments</strong> (under agreement) </li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /> <strong>Scalable operation for large multi-entity organizations</strong></li>
            <li style={{ listStyle: 'none', marginBottom: 10, gap: 2 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main , position:'relative', top:5  }} /><strong> Metrics per employee and branch/project comparisons</strong></li>
        </ul>
    }
})