import { NotInterested, CheckOutlined } from "@mui/icons-material"
import { Box } from "@mui/material"

export const passinbizPlansItems = (current: boolean, highlighted: boolean): any => ({
    'es': {
        'freemium': <ul style={{ paddingInlineStart: 0 }}>
            <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Emisión Apple/Google Wallet.</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box>Validación QR en tiempo real.</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box>Pases digitales</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <NotInterested fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Módulo de eventos</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <NotInterested fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box>Branding personalizado.</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <NotInterested fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Multi-entidad.</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <NotInterested fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box>Emisión de eventos webhook.</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}><NotInterested fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Soporte de desarrollo, bajo convenio.</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Soporte sin desarrollo.</Box></li>
        </ul>,

        'bronze': <ul style={{ paddingInlineStart: 0 }}>
            <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Emisión Apple/Google Wallet.</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box>Validación QR en tiempo real.</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box>Pases digitales</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Módulo de eventos</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box>Branding personalizado.</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Multi-entidad.</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <NotInterested fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box>Emisión de eventos webhook.</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}><NotInterested fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Soporte de desarrollo, bajo convenio.</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Soporte sin desarrollo.</Box></li>
        </ul>,

        'enterprise': <ul style={{ paddingInlineStart: 0 }}>
            <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Emisión Apple/Google Wallet.</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box>Validación QR en tiempo real.</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box>Pases digitales</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}><CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Módulo de eventos</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box>Branding personalizado.</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Multi-entidad.</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box>Emisión de eventos webhook.</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Soporte de desarrollo, bajo convenio.</Box></li>
            <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Soporte sin desarrollo.</Box></li>
        </ul>
    },
    'en':  {
    'freemium': <ul style={{ paddingInlineStart: 0 }}>
        <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Apple/Google Wallet issuance.</Box></li>
        <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Real-time QR validation.</Box></li>
        <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Digital passes</Box></li>
        <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <NotInterested fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Events module</Box></li>
        <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <NotInterested fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Custom branding.</Box></li>
        <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <NotInterested fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Multi-entity.</Box></li>
        <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <NotInterested fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Webhook event emission.</Box></li>
        <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}><NotInterested fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Development support, under agreement.</Box></li>
        <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Support without development.</Box></li>
    </ul>,

    'bronze': <ul style={{ paddingInlineStart: 0 }}>
        <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Apple/Google Wallet issuance.</Box></li>
        <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Real-time QR validation.</Box></li>
        <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Digital passes</Box></li>
        <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Events module</Box></li>
        <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Custom branding.</Box></li>
        <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Multi-entity.</Box></li>
        <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <NotInterested fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Webhook event emission.</Box></li>
        <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}><NotInterested fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Development support, under agreement.</Box></li>
        <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Support without development.</Box></li>
    </ul>,

    'enterprise': <ul style={{ paddingInlineStart: 0 }}>
        <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Apple/Google Wallet issuance.</Box></li>
        <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Real-time QR validation.</Box></li>
        <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Digital passes</Box></li>
        <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}><CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Events module</Box></li>
        <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Custom branding.</Box></li>
        <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Multi-entity.</Box></li>
        <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Webhook event emission.</Box></li>
        <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Development support, under agreement.</Box></li>
        <li style={{ listStyle: 'none', marginBottom: 10, display:'flex', gap: 10 }}> <CheckOutlined fontSize="small" sx={{ color: (theme) => current ? theme.palette.text.primary : highlighted ? "#FFF" : theme.palette.primary.main, position: 'relative', top: 5 }} /> <Box> Support without development.</Box></li>
    </ul>
}
})